Mobile first version
AJ193/Portfolio pull request #1
Opened 2023-01-12 16:05 UTC by AJ193

In this branch i pushed my completed project.

- modify CSS file
- modify HTML file
- add images

2023-01-12 16:33 UTC, GedeonTS requested changes
# INVALID REVIEW REQUEST

Hi @AJ193 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
<Img src="https://media.giphy.com/media/11tVh1XRNAunYI/giphy.gif">
## Invalid Code Review Request

You have submitted a project, that has an unprofessional README file, Kindly make sure all the sections of the Microverse template are present and replace or delete the logo above. Only the FAQ section is optional

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-12 18:43 UTC, TuyishimireEric requested changes
# Status: REQUIRED CHANGES :recycle: 
### Hi  @AJ193   👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Required Changes ♻️

- Check the comments below 👇

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 18:43 UTC, TuyishimireEric commented on index.html
> +<!-- about section -->
- [ ] I think it would be better to use the ```<header>``` tag as the ```<header>``` element can define a global site header, you may try to use it to replace the ```<div>``` tag for this section 😎😎

2023-01-12 18:43 UTC, TuyishimireEric commented on index.html
> +            <li class="box1">John Doe</li>
- [ ] Kindly this is considered as our site logo, and I think an ```<a>``` tag should be added to the site logo to create a link back to the homepage of the website. 👍 
   
    _This allows users to easily navigate back to the homepage from any other page on the website. Additionally, it also helps with SEO by creating a clear hierarchy and structure for search engines to understand the website. 👍_

Kindly follow this [link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) for more

2023-01-12 18:43 UTC, TuyishimireEric commented on index.html
> +        </ul>
- [ ] Currently, the hamburger button is missing on your website toolbar, And in order to replicate the given Figma design, I think it would be better to use the proper icon provided on Figma or you try to download a matching icon to make your toolbar more professional 👍 👍 
- [ ] I think it would be better also to use the same **margin, Fonts** and **colors** provided by the Figma design, As you can see 👇 👇 you may try to replicate the chosen design

### Your design
![image](https://user-images.githubusercontent.com/102757126/212147864-aed12da4-17f2-4203-9bae-dcee4ed3ad85.png)
### Figma design
![image](https://user-images.githubusercontent.com/102757126/212147962-61c36cba-4db0-4e18-93e4-e5669e1b95e4.png)

2023-01-12 18:43 UTC, TuyishimireEric commented on index.html
> +<img src="images/Illustration-mobile.png" alt="Illustration" class="image-ils">
- [ ] I think it would be better to use the ```background-image``` as decorations are always background images, not an ```<img>``` tag, and using CSS to set background images provides more flexibility, better performance, and better accessibility than using an HTML ```img``` tag. 😉😉

2023-01-12 18:43 UTC, TuyishimireEric commented on index.html
> +        I'm Ghulam Shabbir</h2>
- [ ] Kindly I think it would be better to replace this ```h2``` with a ```h1``` tag, If you want that google (and other search engines) to know about a specific topic, in this case, you, use an ```h1``` tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info. 😉😎

2023-01-12 18:43 UTC, TuyishimireEric commented on style.css
> +  background: black;
- [ ] I think it would be better to use the same **Font, colors** and margins to all your page to replicate the Figma design adjustments to your styling to replicate the Figma design 👍 👍 

### Your design
![image](https://user-images.githubusercontent.com/102757126/212151804-20fddefa-4684-45da-8e4e-cbae220c4792.png)

### Figma design
![image](https://user-images.githubusercontent.com/102757126/212151914-66937331-ba64-45de-b06d-e35d22d60e45.png)

2023-01-13 11:34 UTC, algerina requested changes
Hi @joshualyngdoh  ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

STATUS: REQUEST CHANGES :recycle: 

<img src="https://media0.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/>

Highlights

- [x]  All linters checks are green :heavy_check_mark: 
- [ ]  Descriptive PR title and summary :+1: 


## REQUIRED CHANGES  :recycle: 

- [x]  You have a white margin all over your About page, kindly consider deleting it.

Check the comments under the review.


 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-01-13 11:34 UTC, algerina commented on index.html
> +        </ul>
- [ ] The Logo and the hamburger menu are not displayed, kindly add them to the nav bar so that your project will meet the requirements.

 
![mob1](https://user-images.githubusercontent.com/53347966/212311025-ae2a24fa-ec15-47b7-ab59-f259b58281ee.JPG)

2023-01-13 11:50 UTC, AJ193 commented on index.html
> +        </ul>
@algerina I have already added them but I don't know why it is not showing on your side
![IMG-20230113-WA0005](https://user-images.githubusercontent.com/119049613/212313809-7455a473-1654-4c73-9409-cb48694a8832.jpg)

2023-01-13 12:49 UTC, algerina commented on index.html
> +        </ul>
@AJ193 I tried many times but it's not working. The issue is on the image link, kindly change `src="/images/Toolbar - Dark - Compact.png"` with `src="./images/Toolbar - Dark - Compact.png"` and it will work perfectly.

2023-01-13 20:12 UTC, nicupop729 reviewed
Hello @AJ193  👋,

_This is an additional review as a result of the second opinion request._

Kudos for the great effort put in place for this project! :clap:

I need to inform you that you should not push commits after you received a review you don't understand or you don't agree with if you plan to ask for a Second Opinion Review. Otherwise, it means that you agree with the feedback you received from the reviewer and the Second Opinion is redundant then.

Kindly note that your project is not mobile-view responsive. Users don't have the same mobile screen size. That's why we are learning in this module to build a modern responsive design with the use of Flexbox and Grid. The hamburger button should not have a fixed position but should adapt to the screen of the user.
I am talking here about screen sizes from 375px to 750px.

When ready, kindly ask for another review in your dashboard.

Keep rocking 🚀!

2023-01-14 10:40 UTC, Tadesse-Alemayehu requested changes
### Hi @AJ193 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![199733072-bdacca19-8df9-43a7-be93-3aff2f1c15c8](https://user-images.githubusercontent.com/69077061/204107907-c2532abb-b23d-4fda-88f0-1ec9c7b71971.gif)

 ## Highlights
 - [ ] Good job making most of the changes requested by the previous reviewer. 🙏
 - [ ] Good job overall following the template design 💯
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  Good commit history 🥇
 - [ ]  All linters passed 🥇

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 10:40 UTC, Tadesse-Alemayehu commented on styles.css
> +}
#### Good job adding the logo and the icon @AJ193, I just have a few simple changes to suggest you make, I know this might be intimidating to go through lots of changes but please understand we are trying to make sure you have learned as much as expected.  Please consider fixing the following 
- [ ] Good job making the requested changes and adding the Logo and the hamburger menu, But in doing so I see you make the background for the nav to `background: #fff` this makes your `heading` section white and it's not the same as the Figma design. Please use `background: #3C3A39` for your nave bar. 
- [ ] for the `Logo` please make the text color white (`color: white`) and font-family `Roboto` (`font-family: Roboto;`)
- [ ] for the `hamburger ` Please use a white icon. 
> Your design is almost done @AJ193, This are just minor styles to make sure you have an awesome design. 🙌
### Your navbar 
![Screenshot 2023-01-14 133430](https://user-images.githubusercontent.com/69077061/212467820-bbc63385-cdc2-4b59-89c3-ec5b842f428c.png)
### Figma navbar
![Screenshot 2023-01-14 133447](https://user-images.githubusercontent.com/69077061/212467826-ab440885-ba3f-4f1c-9e57-78379a782817.png)

2023-01-17 12:06 UTC, didierganthier approved these changes
Hi @AJ193 ,

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif" />

## Highlights
- Linters Passing ✔️ 
- Descriptive PR ✔️ 
- Correct GitHub flow ✔️ 

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Once again, congratulations on completing this project! 🎉

2023-01-17 12:29 UTC, merged