CONTACT-FORM
AJ193/Portfolio pull request #3
Opened 2023-01-24 15:50 UTC by AJ193

### ADDITION OF CONTACT FORM IN MY MOBILE PORTFOLIO PROJECT
### General requirements

- Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).

- Make sure that you used correct [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md).

- Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

- HTML/CSS requirements

- Follow our list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

### Project requirements

- The section you need to build for this milestone is:
- the contact form:
- Form
- and the footer (if present in the design)
We included a screenshot of Template 1 for reference, but you should follow the template that you chose.

### Make sure that:

- Name field accepts up to 30 chars.

- Email field accepts only emails.

- Message field accepts up to 500 chars.

- All fields have placeholder text.

- All fields have the correct type.

- A user cannot submit the form if one or more of the fields is empty.

- Collect data by using the [Formspree service](https://formspree.io/html).

- In order to lay out the elements on the page you should use Flexbox.

- You don't need to implement any functionality that requires JavaScript.

- You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

- Implement the button interactions (enable, hover, etc.).

2023-01-24 15:59 UTC, amejid reviewed
Hi @AJ193, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [x] You have submitted a project, that has commits from only one person. As stated in the project requirements the project is a collaborative project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-25 08:28 UTC, IngDavidTM requested changes
## Hi @AJ193  and @egichuhis  🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 08:28 UTC, IngDavidTM commented on index.html
> +                <input class="border-none-1" type="text" name="name" placeholder="Full name">
- [ ] While you make a great effort in creating the input element :+1:, as a [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md) name input should have `maxlength="30"` and `required` attributes to validate the form before it is sent :+1:

2023-01-25 08:28 UTC, IngDavidTM commented on index.html
> +                <textarea class="border-none-3" name="message" rows="8" cols="39" maxlength="200">Enter text here</textarea>
- [ ] While you make did a good job `<textarea>` here  :+1:, as a [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md) message should have `maxlength="500"` and `required` attributes to validate the form before it is sent :+1:

2023-01-25 08:28 UTC, IngDavidTM commented on index.html
> +    </footer>
- [ ] Good job styling your contact form but as you can see below there is an empty space after the last section that should be removed to match as much as possible with the Figma template and improve UX :+1: 

**Your design**

![Screenshot from 2023-01-25 03-25-34](https://user-images.githubusercontent.com/105117832/214514342-be2c9365-6aba-447d-ab2b-eff8162f0bcc.png)

2023-01-25 08:28 UTC, IngDavidTM commented on index.html
> +            <button class="form-button" type="submit">
- [ ] You did a wonderful job styling the submit button, but as a project requirement, you should add some button interactions such as `hover`, and `active` (when it's pressed), as shown in the Figma template :+1: .

![Screenshot from 2023-01-17 05-07-39](https://user-images.githubusercontent.com/105117832/214514872-95ebe214-7fc4-43be-a29b-79507a565e15.png)

2023-01-25 10:24 UTC, AJ193 commented on index.html
> +    </footer>
@IngDavidTM i dont know what to do please guide me I can not understand !

2023-01-25 10:34 UTC, IngDavidTM commented on index.html
> +    </footer>
Hi @AJ193 I think that you should check your CSS file, maybe you set a fixed height in another element an that’s why there are an empty space after your portfolio

2023-01-25 10:36 UTC, IngDavidTM commented on index.html
> +    </footer>
You can check this [video](https://youtu.be/oRKlKhFt2Rg) to learn how to debug your CSS using ‘Inspect element’ 👍

2023-01-25 11:19 UTC, AJ193 commented on index.html
> +    </footer>
@IngDavidTM thanks issue resolved.

2023-01-25 11:52 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @AJ193, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 11:52 UTC, Qoosim commented on index.html
> +            </div>
- [ ] As requested by the previous reviewer, it is part of project requirements to add `required` attribute to all the form input fields to prevent empty submission. Kindly add `required` attribute to every input tags in your form.

![required](https://user-images.githubusercontent.com/26597432/214556437-4f853c35-eeea-4e94-b308-3139f2ed55d5.png)

2023-01-25 11:52 UTC, Qoosim commented on index.html
> +            </button>
- [OPTIONAL] I would also recommend your to consider making your `Get in touch` button to be at the center of your page as we have it on the figma design.

### Your Design
![your-form](https://user-images.githubusercontent.com/26597432/214555515-b21dab95-8726-470a-ad42-e33b0f1c000b.png)

### Figma Design 
![temp-form](https://user-images.githubusercontent.com/26597432/214555565-1b3994ca-d2c8-4abe-9bd3-261b2fc6cd40.png)

2023-01-25 12:35 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @AJ193, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - No linter errors. ✔️
 - Good README file. ✔️
 - Correct GitHub Flow. ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 12:35 UTC, leonardodiasb commented on index.html
> +                <textarea class="border-none-3" name="message" rows="8" cols="39" maxlength="500">Enter text here</textarea>
- [ ] Unfortunately, I cannot approve your project because as the last code reviewers mentioned, the user cannot submit the form if one or more fields are empty(as the project requirement mentions). The `textarea` tag is an important field for the contact form and the user can submit the form with no message. Kindly add the `required` attribute to this field too.

2023-01-25 13:01 UTC, AlphaNtihinduka approved these changes
# STATUS: APPROVED :green_circle: :clap: 
## Hi @AJ193 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Your project is professional :heavy_check_mark: 
- Your repo is professional :heavy_check_mark: 
- Well-structured files :heavy_check_mark: 
- Professional README.md file 💯
- No linter errors :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
### Danger zone ❌ 
- Kindly refer to the inline optional suggestions made. Ensure to apply the [OPTIONAL] suggestions submitted by previours reviewers to have a professional project that suits recruiters' needs.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

2023-01-25 13:03 UTC, merged